### ISSUE TITLE
Gestión de errores

### ISSUE THREAD

**Issue by ruzafa8** [ruzafa8/minishell#25]
Gestión de errores:
 - Si un archivo no existe, mostrar el error del archivo, y no se ejecuta.
 - Si un comando tiene algún problema, mostrar el error de ese comando.
 - ¿Qué pasa si intento leer de 2 archivos, el primero no existe y el segundo sí?
 - ¿Qué pasa si intento escribir en 2 archivos, el primero no existe y el segundo sí? ¿Y si el primero existe y el segundo no?
 - En el pipe, los que tengan error de archivo no se ejecutan, ¿todos se van a ejecutar independientemente de que un comando falle?

**Comment by amorilla42** [comment]
los errores del CD que se printeen
