### ISSUE TITLE
parser error hadling

### ISSUE THREAD

**Issue by ruzafa8** [ruzafa8/minishell#61]
Los errores del parser y el lexer no van al stderror.

Además, hay casos en los que el parser no da error cuando debería, i. e. `wc -l <`

**Comment by amorilla42** [comment]
megusta

**Comment by amorilla42** [comment]
![Image](https://github.com/ruzafa8/minishell/assets/124530018/c8627b3f-35bb-47ad-bb5f-959f06fe5424)
